"""Add Wallet table

Revision ID: 17be33d7ae33
Revises: 
Create Date: 2025-01-15 15:41:58.047922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17be33d7ae33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('wallet_uuid', sa.String(), nullable=False),
    sa.Column('total', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('wallet_uuid'),
    sa.UniqueConstraint('wallet_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
